
var tipuesearch = {"pages": [

{"title": "	Alien: Rogue Incursion Evolved Edition	", "text": "	Alien: Rogue Incursion is a virtual reality game developed and published by Survios.	", "img": "img/	Alien Rogue Incursion Evolved Edition.jpg	", "tags": "	PlayStation 5, PC, Xbox Series X	", "note": "		", "url": "	index.html#:~:text=Alien: Rogue Incursion Evolved Edition	"},
{"title": "	FINAL FANTASY TACTICS - The Ivalice Chronicles	", "text": "	Developed by Square Enix, the remaster includes an updated script and story, gameplay additions including an easier difficulty and options to increase field visibility, updated graphics, and full voice acting in English and Japanese.	", "img": "img/	FINAL FANTASY TACTICS - The Ivalice Chronicles.jpg	", "tags": "	PlayStation 5, PlayStation 4, Xbox Series X, PC, Nintendo Switch, Nintendo Switch 2	", "note": "		", "url": "	index.html#:~:text=FINAL FANTASY TACTICS - The Ivalice Chronicles	"},
{"title": "	LEGO Party!	", "text": "	LEGO Party! is a party game developed by SMG Studio and published by Fictions.	", "img": "img/	LEGO Party!.jpg	", "tags": "	PlayStation 5, PlayStation 4, Xbox Series X, PC, Xbox One, Nintendo Switch	", "note": "		", "url": "	index.html#:~:text=LEGO Party!	"},
{"title": "	Nicktoons & The Dice of Destiny	", "text": "	Nicktoons & The Dice of Destiny is an action role-playing crossover game developed by Petit Fabrik and Fair Play Labs and published by GameMill Entertainment.	", "img": "img/	Nicktoons & The Dice of Destiny.jpg	", "tags": "	Nintendo Switch, PlayStation 5, PC, Xbox Series X	", "note": "		", "url": "	index.html#:~:text=Nicktoons & The Dice of Destiny	"},
{"title": "	Train Sim World 6	", "text": "	Train Sim World (abbreviated to TSW) is a series of train-simulation games developed by Dovetail Games.	", "img": "img/	Train Sim World 6.jpg	", "tags": "	PC, PlayStation 5, PlayStation 4, Xbox One, Xbox Series X	", "note": "		", "url": "	index.html#:~:text=Train Sim World 6	"},
{"title": "	Unyielder	", "text": "	UNYIELDER is an intense Single-Player Boss-rush Movement FPS in the form of an absurd and exploitable Rogue-Looter.	", "img": "img/	Unyielder.jpg	", "tags": "	PC	", "note": "		", "url": "	index.html#:~:text=Unyielder	"},
{"title": "	Phasmophobia	", "text": "	Phasmophobia is a paranormal horror game developed and published by British indie game studio Kinetic Games.	", "img": "img/	Phasmophobia.jpg	", "tags": "	Microsoft Windows, PlayStation 5, Xbox Series X/S	", "note": "		", "url": "	index.html#:~:text=Phasmophobia	"},
{"title": "	Black Myth: Wukong	", "text": "	Black Myth: Wukong is a 2024 action role-playing game developed and published by Game Science.	", "img": "img/	Black Myth Wukong.jpg	", "tags": "	PlayStation 5, Windows, Xbox Series X/S	", "note": "		", "url": "	index.html#:~:text=Black Myth: Wukong	"},
{"title": "	Hogwarts Legacy	", "text": "	Hogwarts Legacy is a 2023 action role-playing game developed by Avalanche Software and published by Warner Bros. Games under its Portkey Games label.	", "img": "img/	Hogwarts Legacy.jpg	", "tags": "	PS5, Windows, Xbox Series X/S, PS4, Xbox One, Nintendo Switch, Nintendo Switch 2	", "note": "		", "url": "	index.html#:~:text=Hogwarts Legacy	"},
{"title": "	Pokémon Scarlet and Violet	", "text": "	Pokémon Scarlet and Pokémon Violet are 2022 role-playing video games developed by Game Freak and published by Nintendo and The Pokémon Company for the Nintendo Switch.	", "img": "img/	Pokémon Scarlet and Violet.jpg	", "tags": "	Nintendo Switch	", "note": "		", "url": "	index.html#:~:text=Pokémon Scarlet and Violet	"},
{"title": "	Elden Ring	", "text": "	Elden Ring is a 2022 action role-playing game developed by FromSoftware and published by Bandai Namco Entertainment.	", "img": "img/	Elden Ring.jpg	", "tags": "	PlayStation 4, PlayStation 5, Windows, Xbox One, Xbox Series X/S, Nintendo Switch 2	", "note": "		", "url": "	index.html#:~:text=Elden Ring	"},
{"title": "	Call of Duty: Vanguard	", "text": "	Call of Duty: Vanguard is a 2021 first-person shooter game developed by Sledgehammer Games and published by Activision.	", "img": "img/	Call of Duty Vanguard.jpg	", "tags": "	PlayStation 4, PlayStation 5, Windows, Xbox One, Xbox Series X/S	", "note": "		", "url": "	index.html#:~:text=Call of Duty: Vanguard	"},
{"title": "	Cyberpunk 2077	", "text": "	Cyberpunk 2077 is a 2020 action role-playing game developed by CD Projekt Red and published by CD Projekt.	", "img": "img/	Cyberpunk 2077.jpg	", "tags": "	PlayStation 4, Windows, Xbox One, PlayStation 5, Xbox Series X/S, Nintendo Switch 2, macOS	", "note": "		", "url": "	index.html#:~:text=Cyberpunk 2077	"},
{"title": "	Call of Duty: Black Ops Cold War	", "text": "	Call of Duty: Black Ops Cold War is a 2020 first-person shooter game co-developed by Treyarch and Raven Software and published by Activision.	", "img": "img/	Call of Duty Black Ops Cold War.jpg	", "tags": "	PlayStation 4, PlayStation 5, Windows, Xbox One, Xbox Series X/S	", "note": "		", "url": "	index.html#:~:text=Call of Duty: Black Ops Cold War	"},
{"title": "	Animal Crossing: New Horizons	", "text": "	Animal Crossing: New Horizons is a 2020 social simulation game developed and published by Nintendo for the Nintendo Switch.	", "img": "img/	Animal Crossing New Horizons.jpg	", "tags": "	Nintendo Switch	", "note": "		", "url": "	index.html#:~:text=Animal Crossing: New Horizons	"},
	
]};
