
var tipuesearch = {"pages": [

{"title": "	Adobe Photoshop	", "text": "	Adobe Photoshop is a raster graphics editor developed and published by Adobe for Windows and macOS. It was created in 1987 by Thomas and John Knoll. It is the most used tool for professional digital art, especially in raster graphics editing, and its name has become genericised as a verb (e.g. 'to photoshop an image', 'photoshopping', and 'photoshop contest') although Adobe disapproves of such use.	", "img": "img/	Adobe Photoshop.jpg	", "tags": "	Raster Graphics Editor	", "note": "		", "url": "	index.html#:~:text=Adobe Photoshop	"},
{"title": "	Apple Watch	", "text": "	The Apple Watch is a brand of smartwatch products developed and marketed by Apple. It incorporates fitness tracking, health-oriented capabilities, and wireless telecommunication, and integrates with watchOS and other Apple products and services. The Apple Watch was released in April 2015, and quickly became the world's best-selling wearable device: 4.2 million were sold in the second quarter of fiscal 2015, and more than 115 million people were estimated to use an Apple Watch as of December 2022. Apple has introduced a new generation of the Apple Watch with improved internal components each September – each labeled by Apple as a 'Series', with certain exceptions.	", "img": "img/	Apple Watch.jpg	", "tags": "	Smartwatch	", "note": "		", "url": "	index.html#:~:text=Apple Watch	"},
{"title": "	Canon Cameras	", "text": "	Canon has been manufacturing and distributing digital cameras since 1984, starting with the RC-701. The RC series was followed by the PowerShot and Digital IXUS series of digital cameras. Canon also developed the EOS series of digital single-lens reflex cameras (DSLR) which includes high-end professional models.	", "img": "img/	Canon Cameras.jpg	", "tags": "	Cameras	", "note": "		", "url": "	index.html#:~:text=Canon Cameras	"},
{"title": "	Google Chrome	", "text": "	Google Chrome is a web browser developed by Google. It was first released in 2008 for Microsoft Windows, built with free software components from Apple WebKit and Mozilla Firefox. Versions were later released for Linux, macOS, iOS, iPadOS, and also for Android, where it is the default browser. The browser is also the main component of ChromeOS, where it serves as the platform for web applications.	", "img": "img/	Google_Chrome_icon_(February_2022).svg.png	", "tags": "	Web Browser	", "note": "		", "url": "	index.html#:~:text=Google Chrome	"},
	
]};
