
var tipuesearch = {"pages": [

{"title": "	Superman	", "text": "	Superman is a superhero created by writer Jerry Siegel and artist Joe Shuster, first appearing in issue #1 of Action Comics, published in the United States on April 18, 1938. Superman has been regularly published in American comic books since then, and has been adapted to other media including radio serials, novels, films, television shows, theater, and video games. Superman is the archetypal superhero: he wears an outlandish costume, uses a codename, and fights evil and averts disasters with the aid of extraordinary abilities. Although there are earlier characters who arguably fit this definition, it was Superman who popularized the superhero genre and established its conventions. He was the best-selling superhero in American comic books up until the 1980s; it is also the best-selling comic book series in the world with 600 million copies sold.	", "img": "img/	Superman	.jpg", "tags": "		", "note": "		", "url": "	index.html#:~:text=Superman	"},
{"title": "	Spider-Man	", "text": "	Spider-Man is a superhero in American comic books published by Marvel Comics. Created by writer-editor Stan Lee and artist Steve Ditko, he first appeared in the anthology comic book Amazing Fantasy #15 (August 1962) in the Silver Age of Comic Books. Considered one of the most popular and commercially successful superheroes, he has been featured in comic books, television shows, films, video games, novels, and plays.	", "img": "img/	Spider-Man	.jpg", "tags": "		", "note": "		", "url": "	index.html#:~:text=Spider-Man	"},
{"title": "	Lex Luthor	", "text": "	Alexander Joseph 'Lex' Luthor  is a supervillain appearing in American comic books published by DC Comics. Created by writer Jerry Siegel and artist Joe Shuster, the character first appeared in Action Comics #23 (April 1940). He has since endured as the archenemy of Superman. While Superman embodies hope and selflessness, Luthor symbolizes unrestrained ambition and humanity’s belief in the superiority of intellect over superhuman power.	", "img": "img/	Lex Luthor	.jpg", "tags": "		", "note": "		", "url": "	index.html#:~:text=Lex Luthor	"},
{"title": "	Supergirl	", "text": "	Kara Zor-El is the original version of the superheroine Supergirl, appearing in American comic books published by DC Comics. She was created by Otto Binder and designed by Al Plastino. The character first appeared in the story 'The Supergirl from Krypton' in Action Comics #252 (May 1959). She is the biological cousin of Kal-El, who went on to adopt the name of Clark Kent and the superhero identity Superman. Her father, Zor-El, is the brother of Superman's father, Jor-El.	", "img": "img/	Supergirl	.jpg", "tags": "		", "note": "		", "url": "	index.html#:~:text=Supergirl	"},
{"title": "	Shazam	", "text": "	Shazam, also known as Captain Marvel and The Captain, is a superhero in American comic books originally published by Fawcett Comics and currently published by DC Comics. Artist C. C. Beck and writer Bill Parker created the character in 1939. Shazam first appeared in Whiz Comics #2 (cover-dated Feb. 1940), published by Fawcett Comics. Shazam is the alter-ego of William Joseph 'Billy' Batson, a young boy who is granted magical powers by the Wizard by speaking the magic word 'SHAZAM!', an acronym of six 'immortal elders': Solomon, Hercules, Atlas, Zeus, Achilles, and Mercury, and transforms into a costumed adult superhero with various superpowers derived from specific attributes of the aforementioned elders.	", "img": "img/	Shazam	.jpg", "tags": "		", "note": "		", "url": "	index.html#:~:text=Shazam	"},

     
     ]};
