window.categorySites = window.categorySites || {};
window.categorySites['Top Websites'] = [

{ name: "	Google	", url: "	http://www.google.com/	" },
{ name: "	YouTube	", url: "	https://www.youtube.com/	" },
{ name: "	Facebook	", url: "	https://www.facebook.com/	" },
{ name: "	Instagram	", url: "	http://instagram.com/	" },
{ name: "	Wikipedia	", url: "	https://www.wikipedia.com/	" },
{ name: "	ChatGPT	", url: "	https://chatgpt.com/	" },
{ name: "	Billboard Hot 100	", url: "	https://www.billboard.com/charts/hot-100	" },
{ name: "	Genius	", url: "	https://genius.com/	" },
{ name: "	Spotify	", url: "	https://www.spotify.com/	" },
{ name: "	IMDb	", url: "	https://www.imdb.com/	" },
{ name: "	Trakt	", url: "	https://trakt.tv/	" },
{ name: "	Netflix	", url: "	https://netflix.com/	" },
{ name: "	Plex	", url: "	https://www.plex.tv/	" },
{ name: "	Github	", url: "	https://github.com/	" },
{ name: "	Messenger	", url: "	https://www.messenger.com/	" },
{ name: "	WhatsApp	", url: "	https://web.whatsapp.com/	" },
{ name: "	OneDrive	", url: "	https://onedrive.live.com/	" },
{ name: "	Outlook	", url: "	https://outlook.com/	" },
{ name: "	Gmail	", url: "	https://www.gmail.com/	" },
{ name: "	iCloud	", url: "	https://www.icloud.com/	" },
{ name: "	Flaticons	", url: "	https://www.flaticon.com/	" },
{ name: "	Freepik	", url: "	https://www.freepik.com/	" },
{ name: "	AwardSpace	", url: "	https://www.awardspace.com/	" },
{ name: "	Speedtest	", url: "	https://www.speedtest.net/	" },
{ name: "	GO	", url: "	https://www.go.com.mt/	" },
{ name: "	Scan	", url: "	https://www.scanmalta.com/	" },
{ name: "	Times of Malta	", url: "	https://timesofmalta.com/	" },
{ name: "	APS Bank	", url: "	https://www.apsbank.com.mt/	" },
{ name: "	Bank of Valletta	", url: "	https://www.bov.com/	" },
{ name: "	BNF Bank	", url: "	https://www.bnf.bank/	" },
{ name: "	Forge of Empires	", url: "	https://www.forgeofempires.com/	" },
{ name: "	Heroes of history	", url: "	https://un-play.heroesofhistorygame.com/	" },
{ name: "	Rise of Cultures	", url: "	https://eu-game.riseofcultures.com/	" },
{ name: "	Sunrise Village	", url: "	https://eu-game.sunrisevillagegame.com/	" },

];
