
var tipuesearch = {"pages": [

{"title": "	Adobe Photoshop	", "text": "	Adobe Photoshop is a raster graphics editor developed and published by Adobe for Windows and macOS. It was created in 1987 by Thomas and John Knoll. It is the most used tool for professional digital art, especially in raster graphics editing, and its name has become genericised as a verb (e.g. 'to photoshop an image', 'photoshopping', and 'photoshop contest') although Adobe disapproves of such use.	", "img": "img/	Adobe Photoshop.jpg	", "tags": "	Raster Graphics Editor	", "note": "		", "url": "	index.html#:~:text=Adobe Photoshop	"},
{"title": "	Apple Watch	", "text": "	The Apple Watch is a brand of smartwatch products developed and marketed by Apple. It incorporates fitness tracking, health-oriented capabilities, and wireless telecommunication, and integrates with watchOS and other Apple products and services. The Apple Watch was released in April 2015, and quickly became the world's best-selling wearable device: 4.2 million were sold in the second quarter of fiscal 2015, and more than 115 million people were estimated to use an Apple Watch as of December 2022. Apple has introduced a new generation of the Apple Watch with improved internal components each September – each labeled by Apple as a 'Series', with certain exceptions.	", "img": "img/	Apple Watch.jpg	", "tags": "	Smartwatch	", "note": "		", "url": "	index.html#:~:text=Apple Watch	"},
{"title": "	Canon Cameras	", "text": "	Canon has been manufacturing and distributing digital cameras since 1984, starting with the RC-701. The RC series was followed by the PowerShot and Digital IXUS series of digital cameras. Canon also developed the EOS series of digital single-lens reflex cameras (DSLR) which includes high-end professional models.	", "img": "img/	Canon Cameras.jpg	", "tags": "	Cameras	", "note": "		", "url": "	index.html#:~:text=Canon Cameras	"},
{"title": "	Google Chrome	", "text": "	Google Chrome is a web browser developed by Google. It was first released in 2008 for Microsoft Windows, built with free software components from Apple WebKit and Mozilla Firefox. Versions were later released for Linux, macOS, iOS, iPadOS, and also for Android, where it is the default browser. The browser is also the main component of ChromeOS, where it serves as the platform for web applications.	", "img": "img/	Google_Chrome_icon_(February_2022).svg.png	", "tags": "	Web Browser	", "note": "		", "url": "	index.html#:~:text=Google Chrome	"},
{"title": "	GoPro	", "text": "	GoPro, Inc. (marketed as GoPro and sometimes stylized as GoPRO) is an American technology company founded in 2002 by Nick Woodman. It manufactures action cameras and develops its own mobile apps and video-editing software. Founded as Woodman Labs, Inc, the company is based in San Mateo, California.	", "img": "img/	GoPro.jpg	", "tags": "	Action Camera	", "note": "		", "url": "	index.html#:~:text=GoPro	"},
{"title": "	iPad	", "text": "	The iPad is a brand of tablet computers developed and marketed by Apple that run the company's mobile operating systems iOS and later iPadOS. The first-generation iPad was introduced on January 27, 2010. Since then, the iPad product line has been expanded to include the smaller iPad Mini, the lighter and thinner iPad Air, and the flagship iPad Pro models. As of 2022, over 670 million iPads have been sold, making Apple the largest vendor of tablet computers. Due to its popularity, the term 'iPad' is sometimes used as a generic name for tablet computers.	", "img": "img/	iPad.jpg	", "tags": "	Tablet Computer	", "note": "		", "url": "	index.html#:~:text=iPad	"},
{"title": "	iPhone	", "text": "	The iPhone is a line of smartphones developed and marketed by Apple Inc. that run iOS, the company's own mobile operating system. The first-generation iPhone was announced by then–Apple CEO and co-founder Steve Jobs on January 9, 2007, at Macworld 2007, and launched later that year. Since then, Apple has annually released new iPhone models and iOS versions; the most recent models being the iPhone 16 and 16 Plus, alongside the higher-end iPhone 16 Pro and 16 Pro Max, and the lower-end iPhone 16e (which replaced the iPhone SE). As of July 2025, more than 3 billion iPhones have been sold, with Apple being the largest vendor of mobile phones since 2023.	", "img": "img/	iPhone.jpg	", "tags": "	Smartphone	", "note": "		", "url": "	index.html#:~:text=iPhone	"},
{"title": "	LEGO	", "text": "	Lego is a line of plastic construction toys manufactured by the Lego Group, a privately held company based in Billund, Denmark. Lego consists of variously coloured interlocking plastic bricks made of acrylonitrile butadiene styrene (ABS) that accompany an array of gears, figurines called minifigures, and various other parts. Its pieces can be assembled and connected in many ways to construct objects, including vehicles, buildings, and working robots. Assembled Lego models can be taken apart, and their pieces can be reused to create new constructions.	", "img": "img/	LEGO.jpg	", "tags": "	Construction Toy Set	", "note": "		", "url": "	index.html#:~:text=LEGO	"},

	
]};
