
var tipuesearch = {"pages": [

{"title": "	PGO	", "text": "	PGO Automobiles is a French car manufacturer, producing exclusive series' of sports cars. The brand operates in the same special market as Wiesmann, and Donkervoort. Their cars are considered an appropriate solution for connoisseurs seeking individuality and style.	", "img": "img/	PGO.jpg	", "tags": "		", "note": "		", "url": "	index.html#:~:text=PGO	"},
{"title": "	Renault	", "text": "	Renault S.A., commonly referred to as Groupe Renault, is a French multinational corporation and automobile manufacturer established in 1899. The company currently produces a range of cars and vans. It has manufactured trucks, tractors, tanks, buses/coaches, aircraft and aircraft engines, as well as autorail vehicles.	", "img": "img/	Renault.jpg	", "tags": "		", "note": "		", "url": "	index.html#:~:text=Renault	"},
{"title": "	Zenvo	", "text": "	Zenvo Automotive A/S is a Danish sports car manufacturer located in Præstø on the Danish Island of Zealand. Co-founded in 2007 by Jesper Jensen and Troels Vollertsen, the company ran under the name Nordic Sports Car A/S until 2009 when the company was rebranded to Zenvo Automotive to tie in the reveal of the ST1. In June 2018 the company was sold to Czech investors, based in Prague. The name 'Zenvo' is derived from a combination of the last three and first two letters in Vollertsen's last name.	", "img": "img/	Zenvo.jpg	", "tags": "		", "note": "		", "url": "	index.html#:~:text=Zenvo	"},	
{"title": "	Aixam	", "text": "	Aixam-Mega is a French automobile manufacturer based in Aix-les-Bains, Savoie. It was founded in 1983 to make microcars following the acquisition of Arola. On 11 April 2013, US based Polaris Industries announced that it had acquired Aixam-Mega from previous owners Axa Private Equity.	", "img": "img/	Aixam.jpg	", "tags": "		", "note": "		", "url": "	index.html#:~:text=Aixam	"},
{"title": "	Alpine	", "text": "	Société des Automobiles Alpine SAS, commonly known as Alpine, is a French manufacturer of sports cars and racing cars established in 1955. The Alpine car marque was created in 1954.	", "img": "img/	Alpine.jpg	", "tags": "		", "note": "		", "url": "	index.html#:~:text=Alpine	"},
{"title": "	Bolloré	", "text": "	Bolloré SE is a French conglomerate headquartered in Puteaux, on the western outskirts of Paris, France. Founded in 1822, the company has interests in Vivendi, international freight forwarding, oil storage and pipelines in France, solid state batteries, access control systems for buildings, palm oil and rubber in Asia and Africa, olive groves in the US and wine production in France.	", "img": "img/	Bolloré.jpg	", "tags": "	Bollore	", "note": "		", "url": "	index.html#:~:text=Bolloré	"},
{"title": "	Bugatti	", "text": "	Automobiles Ettore Bugatti was a German then French manufacturer of high-performance automobiles. The company was founded in 1909 in the then-German city of Molsheim, Alsace, by the Italian-born industrial designer Ettore Bugatti. The cars were known for their design beauty and numerous race victories. Famous Bugatti automobiles include the Type 35 Grand Prix cars, the Type 41 'Royale', the Type 57 'Atlantic' and the Type 55 sports car.	", "img": "img/	Bugatti_logo.svg.png	", "tags": "		", "note": "		", "url": "	index.html#:~:text=Bugatti	"},
{"title": "	Chatenet	", "text": "	Automobiles Chatenet is a manufacturer of microcars based in the Haute-Vienne department of France. The company was founded in 1984 by Louis-Georges Chatenet.	", "img": "img/	Chatenet.jpg	", "tags": "		", "note": "		", "url": "	index.html#:~:text=Chatenet	"},
{"title": "	Delage	", "text": "	Delage is a French luxury automobile and racecar company founded in 1905 by Louis Delâge in Levallois-Perret near Paris; it was acquired by Delahaye in 1935 and ceased operation in 1953. A new incarnation created by the association which acquired the rights to the name in 1956, 'Les Amis de Delage', was announced in 2019. Delage Automobiles began production with the Delage D12.	", "img": "img/	Delage.jpg	", "tags": "		", "note": "		", "url": "	index.html#:~:text=Delage	"},
{"title": "	De la Chapelle	", "text": "	De la Chapelle is a French independent car builder. Founded in 1975 by Xavier de la Chapelle, a former Venturi director, the brand started as a Bugatti replica maker.<p>The De la Chapelle family have an historic automobile legacy with the Stimula marque.<p>In 1996 they created the Roadster, their second own creation.<p>They also make mini real-cars for children.<p>The Replicas are powered by BMW (Straight-6), the Roadster by Peugeot (Straight-4/V6) and the concept car by Mercedes (V8) or Jaguar (V12).	", "img": "img/	De la Chapelle.jpg	", "tags": "		", "note": "		", "url": "	index.html#:~:text=De la Chapelle	"},
{"title": "	Citroën	", "text": "	Citroën is a French automobile company. The 'Automobiles Citroën' manufacturing company was founded on 4 June 1919 by André Citroën. Citroën has been owned by Stellantis since 2021 and previously was part of the PSA Group after Peugeot acquired 89.95% share in 1976. Citroën's head office is located in the Stellantis Poissy Plant in Saint-Ouen-sur-Seine since 2021 (previously in Rueil-Malmaison) and its offices studies and research in Vélizy-Villacoublay, Poissy (CEMR), Carrières-sous-Poissy and Sochaux-Montbéliard.	", "img": "img/	Citroën.jpg	", "tags": "	Citroen	", "note": "		", "url": "	index.html#:~:text=Citroën	"},
{"title": "	DS	", "text": "	DS Automobiles is a French luxury-premium marque created in 2009. Formerly part of Automobiles Citroën S.A., DS has been a standalone brand ultimately owned by PSA Group, later Stellantis. The independent DS marque was created in 2014 from the former DS subbrand and line of models of Citroën cars made since 2009, although it had been separated from Citroën in Asia since 2012.	", "img": "img/	DS.jpg	", "tags": "		", "note": "		", "url": "	index.html#:~:text=DS	"},
{"title": "	Ligier	", "text": "	Ligier is a French automobile and minibus maker created by former racing driver and rugby player Guy Ligier (1930–2015), specialized in the manufacturing of microcars. Ligier is best known for its involvement in the Formula 1 World Championship between 1976 and 1996.	", "img": "img/	Ligier.jpg	", "tags": "		", "note": "		", "url": "	index.html#:~:text=Ligier	"},
{"title": "	Microcar	", "text": "	Microcar was a French microcar manufacturer. The company was founded in 1980 as a division of Jeanneau, a major sailboat manufacturer. Production moved to a new custom-built factory in September 2000. In September 2008, Microcar was acquired by Ligier Automobiles in a deal backed by the Italian private equity firm 21 Investimenti Partners. The merger created Europe's second-biggest manufacturer of microcars, and largest maker of quadricycles, or 'sans permis' (license-exempt) vehicles. The Microcar and Ligier brands were to retain their separate identities and production facilities. Phillipe Ligier, son of company founder Guy Ligier, is CEO of the expanded Ligier Automobiles.	", "img": "img/	Microcar.jpg	", "tags": "		", "note": "		", "url": "	index.html#:~:text=Microcar	"},
{"title": "	Peugeot	", "text": "	Peugeot is a French automobile brand owned by Stellantis.	", "img": "img/	Peugeot.jpg	", "tags": "		", "note": "		", "url": "	index.html#:~:text=Peugeot	"},
{"title": "	Renault Trucks	", "text": "	Renault Trucks is a French commercial truck manufacturer with corporate headquarters at Saint-Priest near Lyon. Originally part of Renault, it has been a subsidiary of Volvo since 2001.<p>From its beginnings in 1978 to 2002, the company was called Renault Véhicules Industriels (Renault Industrial Vehicles), from 1992 on officially written as Renault V. I.. Until 2002, Renault Véhicules Industriels also manufactured buses.	", "img": "img/	Renault Trucks.jpg	", "tags": "		", "note": "		", "url": "	index.html#:~:text=Renault Trucks	"},
  

]};
