
var tipuesearch = {"pages": [

     {"title": "	Gozo News	", "text": "	Gozo News, for all the latest news from Gozo, Malta and around the world.	", "img": "img/	Gozo News.jpg	", "tags": "		", "note": "		", "url": "	malta.html#:~:text=Gozo News	"},
     {"title": "	Lovin Malta	", "text": "	Lovin Malta is your inside track to everything about the Maltese Islands; from daily local news, to tips about the best places to eat, incisive opinion pieces, human interest stories and celebrity news.	", "img": "img/	Lovin Malta.jpg	", "tags": "		", "note": "		", "url": "	malta.html#:~:text=Lovin Malta	"},
     {"title": "	Malta Daily	", "text": "	Malta Daily is Malta's own news & entertainment hub. Keeping Malta updated daily.	", "img": "img/	maltadaily.jpg	", "tags": "		", "note": "		", "url": "	malta.html#:~:text=Malta Daily	"},
     {"title": "	Malta News Agency	", "text": "	We report the local. We embrace the horizon.	", "img": "img/	mna.png	", "tags": "		", "note": "		", "url": "	malta.html#:~:text=Malta News Agency	"},
     {"title": "	MaltaToday	", "text": "	MaltaToday was first published on Friday, 19 November 1999. It was edited by Saviour Balzan and founded to provide a new, liberal alternative to the English-language press in circulation, by promoting an agenda in favour of EU accession and critical voices excluded from the establishment.	", "img": "img/	MaltaToday.jpg	", "tags": "		", "note": "		", "url": "	malta.html#:~:text=MaltaToday	"},
     {"title": "	NETnews	", "text": "	First with news from Malta, and beyond.	", "img": "img/	NETnews.jpg	", "tags": "		", "note": "		", "url": "	malta.html#:~:text=NETnews	"},
     {"title": "	Newsbook	", "text": "	Newsbook Malta is a bi-lingual news portal (Maltese and English) providing information both on the national as well as the international scene. The basic tenets on which Newsbook Malta is based are that the portal is deemed to be fair, accurate and trustworthy. Newsbook Malta started on the 1st October 2012 and is one of the most sought-after news portals in Malta.	", "img": "img/	newsbook.jpg	", "tags": "		", "note": "		", "url": "	malta.html#:~:text=Newsbook	"},
     {"title": "	ONE	", "text": "	We are ONE	", "img": "img/	one.jpg	", "tags": "		", "note": "		", "url": "	malta.html#:~:text=ONE	"},
     {"title": "	talk.mt	", "text": "	Investigating, Analyzing, Reporting	", "img": "img/	talkmt.jpg	", "tags": "		", "note": "		", "url": "	malta.html#:~:text=talk.mt	"},
     {"title": "	The Malta Herald	", "text": "	Our purpose is to create a global footprint of carefully moderated news, supporting local services and filling news deserts. As we identify and weed out fake news and propaganda we offer the kind of news service that is so needed in the current post-truth era.	", "img": "img/	malta herald.png	", "tags": "		", "note": "		", "url": "	malta.html#:~:text=The Malta Herald	"},
     {"title": "	The Malta Independent	", "text": "	Your source for independent news within the Maltese islands.	", "img": "img/	The Malta Independent.jpg	", "tags": "		", "note": "		", "url": "	malta.html#:~:text=The Malta Independent	"},
     {"title": "	The Shift	", "text": "	The Shift is a community-funded online news portal based in Malta dedicated to investigative journalism and the defence of press freedom.	", "img": "img/	theshift.png	", "tags": "		", "note": "		", "url": "	malta.html#:~:text=The Shift	"},
     {"title": "	Times of Malta	", "text": "	Times of Malta was founded in 1935 by Lord Gerald Strickland, his wife Lady Strickland and daughter Mabel as an English-language daily newspaper. It is the oldest daily newspaper in Malta still in circulation and its website, timesofmalta.com, is the country’s most visited news site.	", "img": "img/	timesofmalta-350x350.png	", "tags": "		", "note": "		", "url": "	malta.html#:~:text=Times of Malta	"},
     {"title": "	TVMnews	", "text": "	The latest news from Malta and around the world.	", "img": "img/	TVMnews.jpg	", "tags": "		", "note": "		", "url": "	malta.html#:~:text=TVMnews	"},
               
     ]};
