
var tipuesearch = {"pages": [
     
     {"title": "	Movies & TV	", "text": "	Movies & TV websites galore! Discover streaming platforms, reviews, trailers, and news. Access Netflix, Hulu, HBO Max, and more. Stream, watch, and enjoy!	", "img": "assets/images/	movies-meta.jpeg	", "tags": "		", "note": "		", "url": "	movies.html	"},
     {"title": "	Movie Studios	", "text": "	Discover the studios behind your favorite films! Get official updates, trailers, and sneak peeks directly from the source. Explore the diverse landscape of movie studios and find your next box office hit!	", "img": "assets/images/	movie-studios-meta.jpeg	", "tags": "		", "note": "		", "url": "	movie-studios.html	"},
     {"title": "	Streaming Platforms	", "text": "	Can't decide where to stream? We've got you covered! Discover the top streaming services with our curated list, featuring exclusive shows, hit movies, and binge-worthy content.	", "img": "assets/images/	streaming-platforms-meta.jpeg	", "tags": "		", "note": "		", "url": "	streaming-platforms.html	"},
     {"title": "	TV Networks	", "text": "	From breaking news to binge-worthy series, find your next TV obsession! This page provides direct links to all the major TV networks, so you can start streaming right away.	", "img": "assets/images/	tv-networks-meta.webp	", "tags": "		", "note": "		", "url": "	tv-networks.html	"},
     {"title": "	Music	", "text": "	Turn up the volume! Access the best music on the web with our one-stop guide to top music websites. Discover new sounds, stream your favorites, and more!	", "img": "assets/images/	music-meta.jpeg	", "tags": "		", "note": "		", "url": "	music.html	"},
     {"title": "	Music Streaming	", "text": "	Find your perfect musical match! Explore the most popular music streaming services, compare features, and discover exclusive offers. Unlimited music awaits!	", "img": "assets/images/	music-streaming-meta.jpeg	", "tags": "		", "note": "		", "url": "	music-streaming.html	"},
     {"title": "	Music Downloading	", "text": "	Download your favorite tunes in a click! Explore top digital music stores and compare prices.	", "img": "assets/images/	music-downloading-meta.webp	", "tags": "		", "note": "		", "url": "	music-downloading.html	"},
     {"title": "	Eurovision Song Contest	", "text": "	Unleash your inner Eurovision fan! Dive into the ultimate archive of every winning song from the contest's vibrant history. Explore winners by year, listen to iconic melodies, and relive unforgettable performances. Plus, explore which countries reign supreme with our breakdown of wins by nation. Celebrate music, diversity, and a touch of friendly competition. Discover your new favorite Eurovision hits today!	", "img": "assets/images/	eurovision-song-contest-meta.jpg	", "tags": "		", "note": "		", "url": "	eurovision-song-contest.html	"},
     {"title": "	Sports	", "text": "	Stay in the game with our curated list of top sports websites. Get instant access to the latest news, scores, standings, and expert analysis, all in one place.	", "img": "assets/images/	sports-meta.jpg	", "tags": "		", "note": "		", "url": "	sports.html	"},
     {"title": "	Sports Tournaments	", "text": "	Experience the world's top tournaments under one roof.	", "img": "assets/images/	sports-tournaments-meta.jpg	", "tags": "		", "note": "		", "url": "	sports-tournaments.html	"},
     {"title": "	Baseball	", "text": "	Baseball is a bat-and-ball sport played on a field by two teams against each other. In baseball, a player on one team throws a small round ball at a player on the other team, who tries to hit it with a bat. Then the player who hits the ball has to run around the field. Players get runs by running around in a full circle around three points on the ground called bases, to back where they started, which is called home plate. They have to do this without getting caught by the players on the other team.	", "img": "assets/images/	top-view-baseball-with-bat-23-2148523292-376x376.jpg	", "tags": "		", "note": "		", "url": "	sports-tournaments.html#Baseball	"},
     {"title": "	Basketball	", "text": "	Basketball is a team sport where one team, usually consisting of five players (unless its a 1v1 2v2 3v3 4v4 were it is 1 player verse 1 player 2 players verse 2 players 3 players verse 3 players and 4 players verse 4 players) in each team, play against each other on a rectangular court. The objective is to get the ball through a hoop mounted high on a backboard on the opponent's side of the court, while preventing the opponent from shooting it into your team's hoop. It is a very popular sport worldwide, played with a round and usually orange(orange-brown) ball that bounces. Basketball players mainly use skills such as dribbling, shooting, running, and jumping. Each made basket is worth two points, while a basket made from beyond the three-point line is worth three points. If a player gets into too much physical contact, they may be given free throws which are worth one point each. The game typically lasts for four-quarters and the team with the most points at the end of the four-quarters win the game. If the score is tied at the end of the game, there will be additional play time, called overtime, to allow one team to win the match.	", "img": "assets/images/	top-view-basketball-with-copy-space-23-2148796951-522x348.jpeg	", "tags": "		", "note": "		", "url": "	sports-tournaments.html#Basketball	"},
     {"title": "	Football	", "text": "	American football, referred to as football in the United States and Canada and also known as gridiron, is a team sport. It is played by two teams with 11 players on each side. American football is played with a ball with pointed ends. Points are scored in many ways, usually by one team getting the ball into the end zone of the other team. The game started in the late 19th century as college football, an American version of rugby football.	", "img": "assets/images/	playing-american-football-rugby-ball-red-blue-background-3d-render-407474-4654-522x348.jpeg	", "tags": "		", "note": "		", "url": "	sports-tournaments.html#Football	"},
     {"title": "	Ice Hockey	", "text": "	Ice hockey is a sport that is played by two teams on ice. The players wear ice skates on their feet and can skate across the ice at very high speeds. They hold hockey sticks, which they use to push, shoot or pass a puck around the ice. The players score by shooting the puck into a net; the goaltenders try to stop them. Six players on each team play at once, but a whole team has over 20 players. Each team has 2 defenders, 3 forwards, and a goalie on the ice at a time. When a player breaks a rule, a referee calls a penalty, and the player has to sit in a penalty box for 2–4 minutes. While the player sits in the penalty box, their team has to play without them, and will have fewer players on the ice until the penalty is over.	", "img": "assets/images/	portrait-boy-teen-hockey-player-training-playing-isolated-green-background-neon-light-155003-45890-376x251.jpeg	", "tags": "		", "note": "		", "url": "	sports-tournaments.html#Ice-Hockey	"},
     {"title": "	Motorsport	", "text": "	Auto racing (also known as automobile racing, autosport or motorsport) is a sport involving racing cars. Auto racing began in France in 1895 and is now one of the world's most popular spectator sports.	", "img": "assets/images/	pink-race-car-with-number-01-side-889227-7807-522x348.jpeg	", "tags": "		", "note": "		", "url": "	sports-tournaments.html#Motorsport	"},
     {"title": "	Soccer	", "text": "	Association football is a sport played between two teams. In the United States, Canada and Australia, it is called soccer. In most other English-speaking countries it is called football. Association football is the most popular sport in the world.	", "img": "assets/images/	flat-lay-football-with-copy-space-23-2148796956-522x348.jpeg	", "tags": "		", "note": "		", "url": "	sports-tournaments.html#Soccer	"},
     {"title": "	Tennis	", "text": "	Tennis is a sport played with a felt-covered rubber ball, a tennis racket, and a court.	", "img": "assets/images/	top-view-one-tennis-ball-23-2148796915-376x376.jpg	", "tags": "		", "note": "		", "url": "	sports-tournaments.html#Tennis	"},
     {"title": "	Gaming	", "text": "	Level up your game! Explore our massive directory of gaming websites, covering every genre, platform, and style. Find news, reviews, guides, communities, and more - all in one place!	", "img": "assets/images/	gaming-meta.jpeg	", "tags": "		", "note": "		", "url": "	gaming.html	"},
     {"title": "	News	", "text": "	Stay informed with breaking news headlines from top sources around the world. Explore diverse perspectives and stay in the know with our curated list of news websites.	", "img": "assets/images/	news-meta.jpeg	", "tags": "		", "note": "		", "url": "	news.html	"},
     {"title": "	Finance	", "text": "	Navigate the world of finance with ease! Explore curated links to top finance websites, covering news, investing, banking, and more. Find the perfect resource for your needs.	", "img": "assets/images/	finance-meta.jpeg	", "tags": "		", "note": "		", "url": "	finance.html	"},
     {"title": "	Technology	", "text": "	Stay ahead of the curve with the latest tech news & insights. Explore curated links to top technology websites, covering everything from gadgets & gaming to software & science.	", "img": "assets/images/	technology-meta.jpg	", "tags": "		", "note": "		", "url": "	technology.html	"},
     {"title": "	Shopping	", "text": "	Shop smarter, not harder! Find all your favorite stores and discover new ones on our comprehensive shopping links page. Compare prices, browse deals, and shop with confidence.	", "img": "assets/images/	shopping-meta.jpg	", "tags": "		", "note": "		", "url": "	shopping.html	"},
     {"title": "	Categories	", "text": "	Discover the best websites in every category! Explore our directory and find top-rated sites for news, shopping, entertainment, and more.	", "img": "assets/images/	categories-meta.jpg	", "tags": "		", "note": "		", "url": "	categories.html	"},
                         
     
     ]};
